# Generated by Django 6.0 on 2025-12-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_members_task_is_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
