# Generated by Django 6.0 on 2025-12-25 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_task'),
        ('tasks', '0002_task_completed_at_task_completed_by_task_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('completed_by__isnull', False), ('is_completed', True)), models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('is_completed', False)), _connector='OR'), name='task_completion_audit_consistency'),
        ),
    ]
